language: go
go_import_path: go.etcd.io/etcd/v3

env:
  - DEP_VERSION="0.4.1"
go:
  - 1.16.3
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - rm -f /tmp/etcd-v3.5.0-linux-amd64.tar.gz
  - rm -rf /tmp/etcd-download-test && mkdir -p /tmp/etcd-download-test
  - curl -L https://storage.googleapis.com/etcd/v3.5.0/etcd-v3.5.0-linux-amd64.tar.gz -o /tmp/etcd-v3.5.0-linux-amd64.tar.gz
  - tar xzvf /tmp/etcd-v3.5.0-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1
  - rm -f /tmp/etcd-v3.5.0-linux-amd64.tar.gz
  - /tmp/etcd-download-test/etcd --version
  - /tmp/etcd-download-test/etcdctl version
  - /tmp/etcd-download-test/etcdutl version
  - /tmp/etcd-download-test/etcd
  - mv /tmp/etcd-download-test/etcd /usr/local/bin/
  etcd
  - ./bin/etcd 
  - go get github.com/skynetservices/skydns
  - cd $GOPATH/src/github.com/skynetservices/skydns
  - go build -v
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce 
  
install:
  - dep ensure
before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v2.3.1/etcd-v2.3.1-linux-amd64.tar.gz -o etcd-v2.3.1-linux-amd64.tar.gz
  - tar xzvf etcd-v2.3.1-linux-amd64.tar.gz
  - ./etcd-v2.3.1-linux-amd64/etcd &
script:
  - docker --version
  - docker buildx create --name samplekit
  - docker buildx use samplekit
  - docker buildx inspect --bootstrap
  - docker login --username=ajv21 -p=Jun21@2021
  - docker buildx build -t ajv21/skydns --platform linux/arm64,linux/amd64 --push .
  - docker buildx rm samplekit
