on:
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u ajv21 -p Jun21@2021
      - name: before install
        run: |
         go get go.etcd.io/etcd/client/v3
         go get github.com/skynetservices/skydns
         go build -v
      - name: build and publish ubuntu image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ajv21/skydns:ubuntu-latest

